#!/bin/sh
set -e
# Automatically added by dh_installsystemd/12.7ubuntu1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'fio.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'fio.service' >/dev/null || true
		deb-systemd-helper unmask 'fio.service' >/dev/null || true
	fi
fi
# End automatically added section
