#!/bin/sh -e

dpkg-maintscript-helper rm_conffile /etc/modprobe.d/mlx4.conf 24-1ubuntu2 kmod -- "$@"

case "$1" in
  purge)
  rm -f /etc/modules
  ;;
esac

# Automatically added by dh_installinit/12ubuntu1
if [ "$1" = "purge" ] ; then
	update-rc.d kmod remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/12ubuntu1
dpkg-maintscript-helper rm_conffile /etc/init/kmod.conf 24-1ubuntu2~ kmod -- "$@"
# End automatically added section


exit 0
