#!/bin/sh

set -e 

[ "$1" != "upgrade" ] && update-alternatives --remove sar /usr/bin/sar.sysstat


# Automatically added by dh_installsystemd/12.7.1ubuntu1
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'sysstat.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdeb/12.7.1ubuntu1
dpkg-maintscript-helper rm_conffile /etc/profile.d/sysstat.sh 11.7.3\~ sysstat -- "$@"
# End automatically added section


exit 0
